- name: Push to OCI
  run: |
    git remote add oci https://${{ secrets.OCI_USERNAME }}:${{ secrets.OCI_TOKEN }}@devops.scmservice.ap-mumbai-1.oci.oraclecloud.com/namespaces/bmvrgmpn2hpv/projects/ci-cd-project/repositories/my-repo.git
    git push oci main --force
